# Generated by Django 4.2.15 on 2025-09-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aassist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alcohol_content', models.FloatField(help_text='Alcohol content as percentage (e.g., 5.0 for 5%)')),
                ('volume_ml', models.IntegerField(help_text='Volume in milliliters')),
                ('calories_per_100ml', models.IntegerField(help_text='Calories per 100ml')),
                ('category', models.CharField(choices=[('beer', 'Beer'), ('wine', 'Wine'), ('spirits', 'Spirits'), ('cocktail', 'Cocktail'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1, help_text='Number of drinks consumed')),
                ('notes', models.TextField(blank=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aassist.drink')),
            ],
        ),
    ]
