# Generated by Django 4.2.15 on 2025-09-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aassist', '0004_alter_drinkconsumption_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
